<a href="https://colab.research.google.com/github/19PA1A02A3/AI-Lab/blob/master/Experiment_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 1 Numpy

## Different ways to create Numpy arrays

###i)Creat a numpy array using list

In [ ]:
 import numpy as np 
p=np.array([1,8,9])
print(p)

[1 8 9]


ii)Add,Remove,Modify array elements add

Add

In [ ]:
 f=np.array([4,1,9])
q=np.append(f,[3,6,8])
print(q)

[4 1 9 3 6 8]


Remove

In [ ]:
 c=np.delete(f,2)
print(c)

[4 1]


Modify

In [ ]:
 c[c>3]=-1
print(c)

[-1  1]


### iii)Arthemetic operations on Numpy array

In [ ]:
 import numpy as np 
l=np.random.random((5,5))
m=np.random.random((5,5))
num_sum=np.add(l,m)
num_diff=np.subtract(l,m)
num_prod=np.multiply(l,m)
num_quo=np.divide(l,m)
num_mod=np.mod(l,m)
num_pow=np.power(l,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)

[[0.99550793 1.05490516 1.06846531 1.45016286 0.74388415]
 [0.48906432 0.31312026 0.17293527 1.2723797  1.33321129]
 [0.52663351 0.69928647 1.09441792 1.54153458 1.11742523]
 [0.95568614 0.85401589 1.48635315 1.2242105  0.20280549]
 [0.52914143 1.6582799  1.24602729 1.1772339  1.03428612]]
[[-0.39519792 -0.27206899 -0.3603967  -0.47964645  0.28215723]
 [ 0.42781025  0.11905707  0.01123526  0.56085989 -0.30518798]
 [ 0.18509436  0.05339761 -0.21422745 -0.26519182  0.32981914]
 [-0.70625507 -0.83794683  0.34401931  0.01364078 -0.06686492]
 [ 0.48108082 -0.23005218 -0.27434798 -0.74350262  0.25871644]]
[[0.20871366 0.25970084 0.25293308 0.4682279  0.11843773]
 [0.01404057 0.02096743 0.00744509 0.32609657 0.42107816]
 [0.06077073 0.12153757 0.28796429 0.57650054 0.28496462]
 [0.10363495 0.00679706 0.5227241  0.37462632 0.00916479]
 [0.01213797 0.67424206 0.3693293  0.20827087 0.2507034 ]]
[[4.31658505e-01 5.89940784e-01 4.95547232e-01 5.02907929e-01
  2.22218232e+00]
 [1.49683861e+01 2.226

###iv)Slicing and Iterating of numpy array

slicing

In [ ]:
 import numpy as np 
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6])

[2 3 4 5 6]


Iterating

In [ ]:
 for x in arr:
  print(x)

1
2
3
4
5
6
7


###v)Matrix operations on Numpy arrays

In [ ]:
 import numpy as np 
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
